config/routes.rb
Rails.application.routes.draw do

    root to: 'tasks#index'
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    get 'register', to: 'users#new'
    
    resources :tasks
    resources :users, only: [:new, :create]
    
   # resources :tasks do
   #     collection do
    #    get 'error'
    #    end
    #end
        
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow
end

app/models/task.rb
class Task < ApplicationRecord
    validates :status, presence: true, length: { maximum: 10 }
    validates :content, presence: true, length: { maximum: 10 }
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :name,presence: true,length: { maximum: 25 }
    
    validates :password,presence: true,length: { in: 6..25 }
    
    validates :email, presence: true, 
                
                
                
                format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                uniqueness: { case_sensitive: false }
    
    has_secure_password
    has_many :tasks
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper

private


    def require_user_logged_in
        unless logged_in?
          
          redirect_to login_path
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    
    
    
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_path
    else
      @error = 'ログインに失敗しました。'
      redirect_to login_path,alert: 'ログインに失敗しました。'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    
  
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      
      session[:user_id] = @user.id
      return true
    else
    
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    #before_action :set_task, only: [:show, :edit, :update, :destroy]
    before_action :require_user_logged_in
    before_action :correct_user, only: [:show, :edit, :update, :destroy]
    
    
    
    def index
        #@tasks = Task.where(status: 'done')
        
        
        if logged_in?
            @task = current_user.tasks.build  
            @tasks = current_user.tasks.order(id: :desc).page(params[:page]) #自分のだけ
        #@tasks = Task.all
       
        
        else
            redirect_to login_path
          #  @tasks = Task.all
        end
    end
    
    
    def show
        
    end

    def new
        @task = Task.new
    end
    
    def create
        
        @task = current_user.tasks.build(task_params)
        
    
        if @task.save
          flash[:success] = 'タスクを登録しました。'
          redirect_to root_url
        else
          #@task = current_user.tasks.order(id: :desc).page(params[:page])
          #flash.now[:danger] = 'タスクの登録に失敗しました。'
          #redirect_to root_url
          flash.now[:danger] = 'task の登録に失敗しました'
          render :new
        end
      
    end
    
    def edit 
       
    end    
    
    
    def update
        
        
        if @task.update(task_params)
           flash[:success] = 'task を更新しました'
           redirect_to @task
        else
            flash.now[:danger] = 'task の更新に失敗しました'
            render :edit
        end
        
    end
    
    def destroy
        
        @task.destroy
        #Task.find(params[:id]).destroy
        
        flash[:success] = 'task を削除しました。'
        redirect_to tasks_url
    end

    private
    
    #def set_task
    #    @task = Task.find(params[:id])
    #end

    def task_params
        params.require(:task).permit(:content, :status)
    end

    def correct_user
        @task = current_user.tasks.find_by(id: params[:id])
        unless @task
            redirect_to root_path
        end
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
   # before_action :require_user_logged_in, only: [:index, :show]
    
    #def index
    #    @users = User.order(id: :desc).page(params[:page]).per(25)
    #end
    
    #def show
    #    @user = User.find(params[:id])
    #end
    
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        
        if @user.save
            flash[:success] = 'ユーザを登録しました。'
            redirect_to login_path
        else
            flash.now[:danger] = 'ユーザの登録に失敗しました。'
            #redirect_to register_path
            render :new
        end
    end

private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
            
end
    

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>

      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
 

<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<a href="/">Tasklist</a>

<% if logged_in? %>

    <%#= link_to 'プロフィール', user_path(current_user) %>
    <%= link_to 'ログアウト', logout_path, method: :delete %>
    <%= current_user.name %>でログイン中！


<% else %>
    <%= link_to '登録', register_path, class: 'nav-link' %>
    <%= link_to 'ログイン', login_path, class: 'nav-link' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'layouts/navbar' %>

    <%= render 'layouts/flash_messages' %>
      
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model:task, local:true) do |t|  %>

    <% if @task.errors.any? %>
        <div id = "error_explanation">
            <ul>        
            <% task.errors.full_messages.each do |msg| %>
                

                    <li><%= msg %></li>
                
                
            <% end %>
            </ul>
        </div>
    <% end %>

    <%= t.label :status,'ステータス'%>
    <%= t.text_field :status %>

    <%= t.label :content,'タスク'%>
    <%= t.text_field :content %>
    
    <%= t.submit '送信' %>
<% end %>

app/views/tasks/_tasks.html.erb
<% tasks.each do |task| %>

    <%= link_to task.user.name, user_path(task.user) %> 
    タスク登録 <%= task.created_at %>
<% end %>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %>のタスク編集ページ</h1>

<%= render 'form',task: @task %>

<%= link_to '戻る',task_path %>

<%= link_to 'tasklistへ',root_path %>

app/views/tasks/index.html.erb
<h1>タスク管理TOP</h1>

<%# if logged_in? %>
  
<%# else %>
      
      <h2><%= current_user.name %>さん、タスクを登録しよう！</h2>
      
      <%= render 'form',task: @task %>


        


<%# end %>
        <h2><%= current_user.name %>さんのタスクリスト！</h2>
        <ul>
            <% @tasks.each do |task|%>
            <li><%= link_to task.id , task_path(task) %>:<%= task.status %> <%= task.content %></li>
            <% end %>
        </ul>




<%#= render 'tasks/tasks', tasks: @tasks %>


<%#= link_to '登録する', register_path %>

<%#= link_to  '新規タスクの投稿', new_task_path %>

app/views/tasks/new.html.erb
<h1>タスク管理TOP</h1>


<h2><%= current_user.name %>さん、タスクを登録しよう！</h2>
      
<%= render 'form',task: @task %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> のタスク詳細ページ</h1>

<p>ステータス：<%= @task.status %></p>
<p>タスク：<%= @task.content %></p>

<%= link_to '一覧に戻る',root_path %>
<%= link_to '編集',edit_task_path(@task) %>
<%= link_to 'タスクを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/users/_formr.html.erb
    <%= form_with(model:user, local:true) do |t|  %>

        <% if @user.errors.any? %>
            <div id = "error_explanation">
                <ul>        
                <% user.errors.full_messages.each do |msg| %>
                    
    
                        <li><%= msg %></li>
                    
                    
                <% end %>
                </ul>
            </div>
         <% end %>
    
    <%= form_with(model: @user, local: true) do |f| %>
      
      
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name %>
      
        <p>
      
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email %>
      
        <p>
    
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password %>
        6文字以上でお願いします
        
        <p>
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation %>
        <p>     

      <%= f.submit '登録' %>
    <% end %>
<% end %>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>

            <%= user.name %>
       
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%= paginate users %>
<% end %>

app/views/users/index.html.erb
<%= link_to 'USER登録へ', register_path %>

<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>登録</h1>
</div>


      <h2>まずは会員登録をしよう！</h2>
      
      <%= render 'formr',user: @user %>
      
 

app/views/users/show.html.erb
<ul>
    
<li>ユーザー名</li>
<%= @user.name %>
<li>登録アドレス</li>
<%= @user.email %>
</ul>



<%= link_to 'USER一覧へ', users_path %>

<%= link_to 'USER登録へ', register_path %>